spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

producer-service:
  url: http://producer:1212

server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.apache.skywalking: INFO
    org.springframework: INFO
    org.springframework.cloud.stream.binder: INFO