spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

consumer-service:
  url: http://consumer:8081

server:
  port: 1212

logging:
  level:
    root: DEBUG
    org.apache.skywalking: INFO
    org.springframework: INFO
    org.springframework.cloud.stream.binder: INFO